image: registry.gitlab.com/shrugal/wow-packager:latest

stages:
  - build
  - deploy

.releases: &releases
  only:
    - /^\d[\d\.]*(-(alpha|beta)\d+)?$/

build:
  stage: build
  only:
    - tags
    - web
  script:
    - release.sh -d
  artifacts:
    paths:
      - .release/LevelSquish/
      - .release/*.zip
  
curseforge:
  <<: *releases
  stage: deploy
  environment:
    name: CurseForge
    url: https://www.curseforge.com/wow/addons/levelsquish
  script:
    - release.sh -ocelzWHG

gitlab:
  <<: *releases
  stage: deploy
  environment:
    name: GitLab
    url: https://gitlab.com/shrugal/LevelSquish/releases
  script:
    - release.sh -ocelzLWH
